fix mission_control mention in README
basecamp/solid_queue pull request #154
Opened 2024-02-19 14:46 UTC by bbonamin

fix mission_control mention in README

mission_control-jobs has been released, so the README needs some minor updates.

2024-02-19 21:19 UTC, rosa commented on README.md
> +We've recently open sourced [mission_control-jobs](https://github.com/basecamp/mission_control-jobs), where, among other things, you're be able to examine and retry/discard failed jobs.
```suggestion
However, we recommend taking a look at [mission_control-jobs](https://github.com/basecamp/mission_control-jobs), a dashboard where, among other things, you can examine and retry/discard failed jobs. 
```

2024-02-19 21:20 UTC, rosa requested changes
Thanks @bbonamin! I had a to-do for me to do this and never got around to it, so thank you! I added a minor suggestion to improve readability and fix a typo.

2024-02-20 12:33 UTC, bbonamin commented
Thank you too for such a great library!

2024-02-20 16:55 UTC, rosa approved these changes
Thank you! 🙏

2024-02-20 17:14 UTC, merged